CapacityReserveMargin: 0
CO2Cap: 0
EnergyShareRequirement: 0
MethodofMorris: 0
MinCapReq: 0
ModelingToGenerateAlternatives: 0
NetworkExpansion: 0
OperationWrapping: 0
OverwriteResults: 0
ParameterScale: 0
PrintModel: 0
Reserves: 0
Solver: CBC
StorageLosses: 0
TimeDomainReduction: 0
TimeDomainReductionFolder: TDR_Results
Trans_Loss_Segments: 0
UCommit: 2
WriteShadowPrices: 0
