@doc raw"""
	write_power(path::AbstractString, inputs::Dict, setup::Dict, EP::Model)

Function for writing the different values of power generated by the different technologies in operation.
"""
function write_power(path::AbstractString, inputs::Dict, setup::Dict, EP::Model)
    gen = inputs["RESOURCES"]
    resources = inputs["RESOURCE_NAMES"]
    zones = zone_id.(gen)

    G = inputs["G"]     # Number of resources (generators, storage, DR, and DERs)
    T = inputs["T"]     # Number of time steps (hours)
    weight = inputs["omega"]

    power = value.(EP[:vP])
    scale_factor = setup["ParameterScale"] == 1 ? ModelScalingFactor : 1
    power *= scale_factor

    df= DataFrame(Resource = resources, Zone = zones)
    df.AnnualSum = power * weight

    _write_timeseries_file(df, power, path, setup, "power")

    return df
end
